In [1]:
import numpy as np

# Generate random float matrix and mask matrix
float_matrix = np.random.rand(3, 3) * 2999.0  # Example matrix of size 3x3
mask_matrix = np.random.randint(2, size=(3, 3), dtype=np.uint8)  # Example mask matrix of size 3x3 with 0s and 1s

# Perform element-wise multiplication
result_matrix = float_matrix * mask_matrix

print("Float Matrix:")
print(float_matrix)
print("\nMask Matrix:")
print(mask_matrix)
print("\nResult Matrix:")
print(result_matrix)

Float Matrix:
[[2293.49910635  389.16763554 2132.32396135]
 [1011.14718031 1389.81602721 1518.75763354]
 [ 766.3138944   379.57143874  845.71224458]]

Mask Matrix:
[[0 0 1]
 [1 0 1]
 [0 0 0]]

Result Matrix:
[[   0.            0.         2132.32396135]
 [1011.14718031    0.         1518.75763354]
 [   0.            0.            0.        ]]


In [ ]:
import cv2
from ultralytics import YOLO
import torch
import numpy as np

model = YOLO("./models/yolov8m-seg.pt")
device = torch.device("mps")
while True:
    # Capture frame-by-frame
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    results = next(
        model.track(
            frame,
            device=device,
            stream=True,
            conf=0.5,
            verbose=False,
            persist=True,
            tracker="bytetrack.yaml",
        )
    )

    if results.masks:
        xy = results.masks.xy
        masks = np.zeros((len(xy), *frame.shape[:2]), dtype=np.uint8)
        print(masks.shape)
        for i, pts in enumerate(xy):
            pts = np.array(pts, dtype = np.int32).reshape(-1, 2)
            cv2.fillPoly(masks[i], [pts], 1)

        
    # Display the resulting frame
    cv2.imshow("frame", frame)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

: 