In [27]:
import numpy as np

#create a binary mask with 0 and 1
#mask = np.random.randint(0, 2, (5, 5))
mask = np.array([[0, 0, 0, 1, 0],[0, 0, 1, 1, 0],[0, 0, 0, 1, 0],[0, 0, 1, 1, 0],[0, 0, 0, 1, 0]])
mask

array([[0, 0, 0, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0]])

In [26]:
#I want to find the minimum x index where mask is equal to 1
#I want to find the maximum x index where mask is equal to 1
xmin = np.min(np.where(mask == 1)[1])
xmax = np.max(np.where(mask == 1)[1])
ymin = np.min(np.where(mask == 1)[0])
ymax = np.max(np.where(mask == 1)[0])
xmin, xmax, ymin, ymax

(2, 3, 0, 4)

In [28]:
ymin, xmin = np.min(np.argwhere(mask), axis=0)
ymax, xmax = np.max(np.argwhere(mask), axis=0)
xmin, ymin, xmax, ymax

(2, 0, 3, 4)

In [43]:
0.1 / (1 / 20)

2.0

In [44]:
2*3.6


7.2

In [37]:
from scipy.spatial import KDTree
import numpy as np
import time

points = np.random.randint(-10, 10, (100, 3))

start = time.time()
for i in range(10000):
    tree = KDTree(points, leafsize=3, compact_nodes=True, balanced_tree=True)

end = time.time()
print("time to build tree: ", (end - start) / 10000)

time to build tree:  1.783308982849121e-05


In [13]:
points

array([[  7,  -8,  -6],
       [ -9,  -6,  -1],
       [  3,   7,  -3],
       [  9,   2,   4],
       [  7,  -6,   0],
       [  3,   4,   2],
       [-10,  -4,   0],
       [ -3,  -9,  -6],
       [ -6,   3,  -8],
       [  7,   7,   9],
       [  7,   2,   1],
       [ -6,   0,   9],
       [  1,   4,  -8],
       [-10,   6,   6],
       [  6, -10,   4],
       [  5,  -6,  -5],
       [  0,  -8,  -6],
       [ -5,   7, -10],
       [ -1,  -8,   5],
       [  0,   4,  -7]])

In [31]:
tree.query(points[0], k = 3, eps=0.1, p=2, distance_upper_bound=10.6, workers=1)

(array([0.        , 3.        , 6.32455532]), array([ 0, 15,  4]))

In [42]:
import numpy as np
from collections import deque

elems = np.random.randint(0, 10, (10, ))
q = deque(elems, maxlen=10)
print(elems)
for i in range(10):
    q.append(i)
    print(q)

[3 6 3 0 5 6 6 4 0 2]
deque([6, 3, 0, 5, 6, 6, 4, 0, 2, 0], maxlen=10)
deque([3, 0, 5, 6, 6, 4, 0, 2, 0, 1], maxlen=10)
deque([0, 5, 6, 6, 4, 0, 2, 0, 1, 2], maxlen=10)
deque([5, 6, 6, 4, 0, 2, 0, 1, 2, 3], maxlen=10)
deque([6, 6, 4, 0, 2, 0, 1, 2, 3, 4], maxlen=10)
deque([6, 4, 0, 2, 0, 1, 2, 3, 4, 5], maxlen=10)
deque([4, 0, 2, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([0, 2, 0, 1, 2, 3, 4, 5, 6, 7], maxlen=10)
deque([2, 0, 1, 2, 3, 4, 5, 6, 7, 8], maxlen=10)
deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
